import Dashboard from "@/components/Dashboard";
import LeftSidebar from "@/components/LeftSidebar";
import RightSidebar from "@/components/RightSidebar";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo_absent.svg" />
      </Head>
      <main className="bg-background w-full h-[100vh] flex flex-row font-poppins">
        <LeftSidebar />
        <Dashboard />

        <RightSidebar />
      </main>
    </>
  );
}
