import Head from "next/head";
import React from "react";

function Header({ title }) {
  return (
    <Head>
      <title>{title.charAt(0).toUpperCase() + title.slice(1)}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/logo_absent.svg" />
    </Head>
  );
}

export default Header;
